call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'mileszs/ack.vim'
Plug 'kien/ctrlp.vim'
Plug 'sickill/vim-pasta'
Plug 'pangloss/vim-javascript'
Plug 'MaxMEllon/vim-jsx-pretty'
Plug 'peitalin/vim-jsx-typescript'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16-vim'
Plug 'Quramy/tsuquyomi'
Plug 'leafgarland/typescript-vim'
Plug 'ianks/vim-tsx'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'TovarishFin/vim-solidity'

call plug#end()

set nocompatible

" color
set t_Co=256
set background=dark
colorscheme distinguished
"
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

set ruler
syntax on

filetype plugin indent on

set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set foldmethod=indent
set autoindent
set smartindent

" needed for fish shell to run some plugins
set shell=/bin/sh

" search
set hlsearch
set incsearch
set ignorecase
set smartcase

" space clears search highlight
:noremap <silent> <Space> :silent noh<Bar>echo<CR>

set backspace=indent,eol,start

" swp files
set backupdir=~/tmp
set directory=~/tmp

" status line
set laststatus=2 
set statusline=[POS=%04l,%04v]\ [LEN=%L]%=%F%m%r%h%w\ \ 

set wildmenu
set wildmode=longest,list

set wildignore+=solidity/build/**,build/**,dist/**,tmp/*,public/javascripts/release/**,public/javascripts/vendor/**,test/fixtures/public/**,node_modules/**,public/instrumented-js/**,vendor/**

" linting
autocmd FileType javascript let b:syntastic_checkers = findfile('.eslintrc.js', '.;') != '' || findfile('.eslintrc', '.;') != '' ? ['eslint'] : ['standard']

" trigger youcompleteme on '.'
" if !exists(“g:ycm_semantic_triggers”)
"   let g:ycm_semantic_triggers = {}
"   endif
" 
" let g:ycm_semantic_triggers[‘typescript’] = [‘.’]

let g:tsuquyomi_disable_default_mappings = 1
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi']
nmap <C-]> :TsuquyomiDefinition<CR>

" force rescan when highlighting. highly intensive.
autocmd BufEnter *.{js,jsx,ts,tsx} :syntax sync fromstart
autocmd BufLeave *.{js,jsx,ts,tsx} :syntax sync clear

" use ag for ack.vim
let g:ackprg = 'ag --nogroup --nocolor --column'

let mapleader = ","

" configure coc language servers
let g:coc_global_extensions = [ 'coc-tsserver', 'coc-json', 'coc-lists' ]

if isdirectory('./node_modules') && isdirectory('./node_modules/prettier')
  let g:coc_global_extensions += ['coc-prettier']
endif

if isdirectory('./node_modules') && isdirectory('./node_modules/eslint')
  let g:coc_global_extensions += ['coc-eslint']
endif

function! ShowDocIfNoDiagnostic(timer_id)
  if (coc#util#has_float() == 0)
    silent call CocActionAsync('doHover')
  endif
endfunction

function! s:show_hover_doc()
  call timer_start(500, 'ShowDocIfNoDiagnostic')
endfunction

autocmd CursorHoldI * :call <SID>show_hover_doc()
autocmd CursorHold * :call <SID>show_hover_doc()

nnoremap <silent> K :call CocAction('doHover')<CR>

" navigate to definitions
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gr <Plug>(coc-references)

" navigate to errors in file
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" nnoremap <silent> <space>d :<C-u>CocList diagnostics<cr>
" nnoremap <silent> <space>s :<C-u>CocList -I symbols<cr>

nmap <leader>do <Plug>(coc-codeaction)

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

nmap <leader>rn <Plug>(coc-rename)

" ctrl-p
if exists("g:ctrlp_user_command")
  unlet g:ctrlp_user_command
endif
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<C-T>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
let g:crlp_max_height = 10
let g:crlp_max_files = 20000
let g:ctrlp_custom_ignore = 'solidity/build\|build\|dist\|node_modules\|DS_Store\|git\|resources/public/js/compiled\|www'

" ignore whitespace in diff mode 
" set diffopt+=iwhite
set diffexpr=DiffW()
function DiffW()
let opt = ""
 if &diffopt =~ "icase"
   let opt = opt . "-i "
 endif
 if &diffopt =~ "iwhite"
   let opt = opt . "-w " " vim uses -b by default
 endif
 silent execute "!diff -a --binary " . opt .
   \ v:fname_in . " " . v:fname_new .  " > " . v:fname_out
endfunction

" tab behavior: indent if at start of line, otherwise do completion
function! InsertTabWrapper()
  let col = col('.') -1
  if !col || getline('.')[col - 1] !~ '\k'
    return "\<tab>"
  else
    return "\<c-p>"
  endif
endfunction
inoremap <tab> <c-r>=InsertTabWrapper()<cr>

" faster scrolling
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

nnoremap <C-D> :qa<CR>

" pane navigation
nnoremap <C-K> <C-W>k
nnoremap <C-J> <C-W>j
nnoremap <C-H> <C-W>h
nnoremap <C-L> <C-W>l

" faster pane resizing
nnoremap <C-W>, 10<C-W><
nnoremap <C-W>. 10<C-W>>
nnoremap <C-W>- 10<C-W>-
nnoremap <C-W>+ 10<C-W>+

" change working directory to that of current file.
cmap cd. lcd %:p:h

" Faster 'next search repeat command' {{{3
nnoremap Q :normal n.<CR>

noremap <Leader>n :setlocal number!<CR>
noremap <Leader>nr :setlocal relativenumber!<CR>
